#!/bin/bash


if [ $# -ne 1 ]; then
   echo 1>&2 Usage: $0 ASCIIDOC_FILE
   exit 127
fi

AD=/home/terry/bin/asciidoc-7.0.0

AD2TXT=$AD/examples/asciidoc2text

LN_FILES="asciidoc2text.sh asciidoc2text.conf"

for file in $LN_FILES 
do
	ln -s $AD2TXT/$file .
done

asciidoc -b html4  $1
./asciidoc2text.sh $1 > $1.ft