#!/bin/bash -x

# You should run this with bash
# Uploads your id_rsa.pub to the specified host, wrapped for readability

USER=computer
HOSTNAME=192.168.1.50

if [ ! -r "${HOME}/.ssh/id_rsa.pub" ]; then
 ssh-keygen -t rsa -b 2048
fi
# Copy the files to the remote servers
UH=$USER@$HOSTNAME

scp ~/.ssh/id_rsa.pub $UH:/tmp/$UH.id_rsa.pub
# Tell the remote host to copy the file over ~ of the current user
ssh $UH "cat /tmp/$UH.id_rsa.pub >> ~/.ssh/authorized_keys; #rm -f /tmp/$UH.id_rsa.pub"

#

if [ $? -eq 0 ]; then
  echo "Success"
fi

