#!/usr/bin/env perl

use strict;

use List::MoreUtils;
use Tie::IxHash;

use local::lib '~/bin';
use MySSH;

#use Data::Dumper;
#die Dumper(\%INC);

my @sshstr;


sub gethosts {
    List::MoreUtils::natatime 2, @MySSH::user;
}

sub printchoices {

  print "\n\n";
  print "ssh hosts\n";
  print "---------\n";

  my $iterator = gethosts;
  my $i;
  while (my ($user,$host) = $iterator->()) {
      my $sshstr = sprintf '%s@%s' , $user, $host;
      printf "[%d] %s\n", $i++, $sshstr;
      push @sshstr, $sshstr;
  }
}

sub prompt {
  print "\n\nssh to: " ;
}


sub getchoice {
  prompt ;
  my $choice = <STDIN> ;
  chomp $choice;
  return $choice;
}



sub mainloop {
  {
    printchoices;
    my $c = getchoice ;
    return $c if $c =~ /^\d+$/ and $c >= 0 and $c <= $#MySSH::user ;
    redo;
  }
}

my $choice = mainloop;
my $sshstr = $sshstr[$choice];
print $sshstr, "\n" ;

if ($ENV{DISPLAY}) {
    system "xterm -title '$sshstr' -e 'ssh -Y $sshstr' &" ;
} else {
    exec 'ssh', '-C', '-A', '-X', $sshstr, '&' ;
}








