#!/usr/bin/env perl

use strict;


use Tie::IxHash;

use local::lib '~/bin';
use MySSH;

#use Data::Dumper;
#die Dumper(\%INC);


my %user;
my $user  = Tie::IxHash->new
    (
     %MySSH::user
    ) ;


my @user_i = $user->Indices ($user->Keys) ;


sub ssh_string {
  my $host = shift;
  my $user = $user->FETCH($host);
  sprintf "%s@%s", $user, $host
}

sub printchoices {

  print "\n\n";
  print "ssh hosts\n";
  print "---------\n";

  for my $i (@user_i) {
      my $host  = $user->Values($i) ;
      my $user  = $user->Keys($i);
      printf "[$i] %s@%s\n" , $user, $host;
  }
}

sub prompt {
  print "\n\nssh to: " ;
}


sub getchoice {
  prompt ;
  my $choice = <STDIN> ;
  chomp $choice;
  return $choice;
}



sub mainloop {
  {
    printchoices;
    my $c = getchoice ;
    return $c if $c =~ /^\d+$/ and $c >= 0 and $c <= $#user_i  ;
    redo;
  }
}

my $c = mainloop;
my $host = $user->Keys($c);
my $sshstr = ssh_string($host) ;


print $sshstr, "\n" ;
if ($ENV{DISPLAY}) {
    system "xterm -title '$sshstr' -e 'ssh -Y $sshstr' &" ;
} else {
    exec 'ssh', '-C', '-A', '-X', $sshstr, '&' ;
}








